name:         Mafia
markdown:     kramdown
permalink:    pretty
exclude:      ["CNAME", "LICENSE", "README.md"]

kramdown:
  auto_ids: false

gems:
  - jemoji
  - jekyll-redirect-from

version:       0.4.3
